Section "InputClass"
        Identifier "stylus touchpad"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
        Option "Tapping" "on"
        Option "TappingDrag" "on"
        Option "TappingDragLock" "off"
        Option "TappingButtonMap" "lrm"
        Option "NaturalScrolling" "false"
        Option "ClickMethod" "clickfinger"
        Option "MiddleEmulation" "on"
        Option "ScrollMethod" "twofinger"
        Option "DisableWhileTyping" "on"
        Option "AccelSpeed" "0.0"
        Option "AccelProfile" "adaptive"
EndSection
